apiVersion: v1
kind: Pod
metadata:
  name: pod-with-env-configmap
spec:
  containers:
    - name: myapp
      image: busybox
      command: ['sh','-c','env && sleep 3600']  
      env:
        - name: API_URL
          valueFrom:
            configMapKeyRef:
              name: app-config-dev  # app-config-prod
              key: api.url
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: app-config-dev # app-config-prod
              key: log.level
