apiVersion: v1
kind: Pod
metatdata:
  name: pod-with-configmap
spec:
  containers:
    - name: myapp
      image: busybox
      command: ['sh','-c','env && slep 3600']  
      env:
        -name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: database.url
        -name: DATABASE_USERNAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: database.username
        -name: DATABASE_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: database.password        
              
              
