apiVersion: v1
kind: Pod
metadata:
  name: pod-with-multi-file-configmap
spec:
  containers:
    - name: myapp
      image: busybox
      command: ['sh','-c','cat /config/app-config.yml && cat /config/log-config.yml && sleep 3600']  
      volumeMounts:
        - name: config-volume
          mountPath: /config
  volumes:
    - name: config-volume
      configMap:
        name: multi-file-config
