apiVersion: v1
kind: Service
metadata:
  name: file-upload-app-service
spec:
  type: NodePort
  selector:
    app: file-upload-app2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30000
