version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
        MYSQL_ROOT_PASSWORD: rootpassword
        MYSQL_DATABASE: borad
    ports:
      - "3306:3306"
    networks:
      - app-network
  app:
    build: .
    container_name: board-app
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
~                     
